### ISSUE TITLE
Sad path testing around filtering is desired. For Part 2, implement filtering tests and to test for the sad path case (e.g. filtering on an empty string, filtering on text that doesn’t return any results).

### ISSUE THREAD

**Issue by nairnairnair** [nairnairnair/whats-cookin#131]
Sad path testing around filtering is desired. For Part 2, implement filtering tests and to test for the sad path case (e.g. filtering on an empty string, filtering on text that doesn’t return any results).

**Comment by Mlberry0205** [comment]
Nice work creating sad paths, team!
